// Generated by CoffeeScript 1.10.0
(function() {
  var ActionBridge, ActionGenerator, PingBridge,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PingBridge = require('./ping-bridge');

  ActionGenerator = require('../actions/action-generator');

  ActionBridge = (function(superClass) {
    extend(ActionBridge, superClass);


    /**
     * @protected
     * @type {Object.<Event>
     */

    ActionBridge.prototype.actions = null;


    /**
     * @override
     */

    function ActionBridge(parent, config, index) {
      var action, actionName, ref;
      ActionBridge.__super__.constructor.call(this, parent, config, index);
      this._initializeChildrenWithGenerator(config, 'actions', ActionGenerator);
      ref = this.actions;
      for (actionName in ref) {
        action = ref[actionName];
        this.on(actionName, action.run);
      }
    }

    return ActionBridge;

  })(PingBridge);

  module.exports = ActionBridge;

}).call(this);

//# sourceMappingURL=action-bridge.js.map
