// Generated by CoffeeScript 1.10.0
(function() {
  var ActionBridge, ActionGenerator, PingBridge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  PingBridge = require('./ping-bridge');

  ActionGenerator = require('../actions/action-generator');

  ActionBridge = (function(superClass) {
    extend(ActionBridge, superClass);


    /**
     * @protected
     * @type {Object.<Event>
     */

    ActionBridge.prototype._actions = null;


    /**
     * @override
     */

    function ActionBridge(parent, config, index) {
      this.notify = bind(this.notify, this);
      var actionConfig, actionGenerator, actions, i, j, len;
      ActionBridge.__super__.constructor.call(this, parent, config, index);
      this._actions = {};
      i = 0;
      actions = this._checkConfig(config, 'actions', 'array', []);
      if (actions) {
        actionGenerator = new ActionGenerator(this);
        this.log('debug', "Construct event objects was started.");
        for (j = 0, len = actions.length; j < len; j++) {
          actionConfig = actions[j];
          this._actions[actionConfig.name] = actionGenerator.generate(this, actionConfig, i);
          this.on(actionConfig.name, this._actions[actionConfig.name].run);
        }
        this.log('debug', "Construct event objects was finished.");
      }
    }

    ActionBridge.prototype.notify = function() {
      var action, args, ref;
      action = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref = this._parent).notify.apply(ref, [action].concat(slice.call(args)));
    };

    return ActionBridge;

  })(PingBridge);

  module.exports = ActionBridge;

}).call(this);

//# sourceMappingURL=action-bridge.js.map
