// Generated by CoffeeScript 1.10.0
(function() {
  var Base, BaseBridge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./../base');

  BaseBridge = (function(superClass) {
    extend(BaseBridge, superClass);


    /**
     * @const
     * @type {Object}
     */

    BaseBridge.prototype.STATUS_TYPE = {
      constructing: {
        label: 'Constructing'
      },
      connecting: {
        label: 'Connecting'
      },
      ready: {
        label: 'Ready'
      },
      error: {
        label: 'Error'
      }
    };


    /**
     * @public
     * @type {Object}
     */

    BaseBridge.prototype.status = BaseBridge.prototype.STATUS_TYPE.constructing;


    /**
     * @protected
     * @type {string}
     */

    BaseBridge.prototype._token = '';


    /**
     * @protected
     * @type {Blynk.Blynk.WidgetBridge}
     */

    BaseBridge.prototype._widgetBridge = null;

    function BaseBridge(parent, config, index) {
      this.connect = bind(this.connect, this);
      BaseBridge.__super__.constructor.call(this, parent, config, index);
      this._token = this._checkConfig(config, 'token', 'string');
      this._widgetBridge = new this.parent.blynk.WidgetBridge(index + 1);
    }


    /**
     * @public
     */

    BaseBridge.prototype.connect = function() {
      this.status = this.STATUS_TYPE.connecting;
      this._widgetBridge.setAuthToken(this._token);
      return this.status = this.STATUS_TYPE.ready;
    };

    return BaseBridge;

  })(Base);

  module.exports = BaseBridge;

}).call(this);

//# sourceMappingURL=base-bridge.js.map
