// Generated by CoffeeScript 1.10.0
(function() {
  var Bridge, PingBridge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PingBridge = require('./ping-bridge');

  Bridge = (function(superClass) {
    extend(Bridge, superClass);


    /**
     * @override
     */

    function Bridge(parent, config, index) {
      this.connect = bind(this.connect, this);
      Bridge.__super__.constructor.call(this, parent, config, index);
    }


    /**
     * @override
     */

    Bridge.prototype.connect = function() {
      this.log('info', "Connect bridge was started.");
      Bridge.__super__.connect.call(this);
      return this.log('info', "Connect bridge was finished.");
    };

    return Bridge;

  })(PingBridge);

  module.exports = Bridge;

}).call(this);

//# sourceMappingURL=bridge.js.map
