// Generated by CoffeeScript 1.10.0
(function() {
  var Bridge, PingBridge,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PingBridge = require('./ping-bridge');

  Bridge = (function(superClass) {
    extend(Bridge, superClass);

    function Bridge() {
      return Bridge.__super__.constructor.apply(this, arguments);
    }

    return Bridge;

  })(PingBridge);

  module.exports = Bridge;

}).call(this);

//# sourceMappingURL=bridge.js.map
