// Generated by CoffeeScript 1.10.0
(function() {
  var BuiltInEventBridge, PingBridge, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  util = require('util');

  PingBridge = require('./PingBridge');

  BuiltInEventBridge = (function(superClass) {
    extend(BuiltInEventBridge, superClass);


    /**
     * @override
     */

    function BuiltInEventBridge(parent, config, index) {
      this.notify = bind(this.notify, this);
      BuiltInEventBridge.__super__.constructor.call(this, parent, config, index);
    }

    BuiltInEventBridge.prototype.notify = function() {
      var args, event, ref;
      event = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref = this._parent).notify.apply(ref, [event].concat(slice.call(args)));
    };

    return BuiltInEventBridge;

  })(PingBridge);

  module.exports = BuiltInEventBridge;

}).call(this);

//# sourceMappingURL=BuiltInEventBridge.js.map
