// Generated by CoffeeScript 1.10.0
(function() {
  var BuiltInEventBridge, CustomEventBridge,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BuiltInEventBridge = require('./BuiltInEventBridge');

  CustomEventBridge = (function(superClass) {
    extend(CustomEventBridge, superClass);


    /**
     * @override
     */

    function CustomEventBridge(parent, config, index) {
      CustomEventBridge.__super__.constructor.call(this, parent, config, index);
    }

    return CustomEventBridge;

  })(BuiltInEventBridge);

  module.exports = CustomEventBridge;

}).call(this);

//# sourceMappingURL=CustomEventBridge.js.map
