// Generated by CoffeeScript 1.10.0
(function() {
  var BaseBridge, TransceiverBridge, uid,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  BaseBridge = require('./base-bridge');

  uid = require('../common/uid');

  TransceiverBridge = (function(superClass) {
    extend(TransceiverBridge, superClass);


    /**
     * @const
     * @type {number}
     */

    TransceiverBridge.prototype.SEND_TIMEOUT = 10000;


    /**
     * @protected
     * @type {Object}
     */

    TransceiverBridge.prototype._sendCallbacks = null;


    /**
     * @override
     */

    function TransceiverBridge(parent, config) {
      this._sendFailureCallback = bind(this._sendFailureCallback, this);
      this.write = bind(this.write, this);
      this.sendCallback = bind(this.sendCallback, this);
      this.send = bind(this.send, this);
      TransceiverBridge.__super__.constructor.call(this, parent, config);
      this._sendCallbacks = {};
    }


    /**
     * @public
     * @param {string} output
     */

    TransceiverBridge.prototype.send = function() {
      var callback, command, failureCallback, i, output, param, params, pin, ref, ref1, requestId;
      command = arguments[0], params = 4 <= arguments.length ? slice.call(arguments, 1, i = arguments.length - 2) : (i = 1, []), callback = arguments[i++], failureCallback = arguments[i++];
      if (command !== 'pi' && this.status !== this.STATUS_TYPES.ready) {
        this.log('warn', "Send command='" + command + "' params=" + (JSON.stringify(params)) + " can not run. Bridge status='" + this.status.label + "' is not ready.");
        return;
      }
      pin = (ref = params[0]) != null ? ref : 0;
      param = (ref1 = params[1]) != null ? ref1 : '';
      while (true) {
        requestId = uid(3);
        if (!this._sendCallbacks[requestId]) {
          break;
        }
      }
      this._sendCallbacks[requestId] = callback;
      output = requestId + "," + command + "," + pin + "," + param;
      setTimeout(this._sendFailureCallback, this.SEND_TIMEOUT, requestId, failureCallback, output);
      this.log('trace', "Send data='" + output + "'");
      return this._widgetBridge.virtualWrite(0, output);
    };

    TransceiverBridge.prototype.sendCallback = function() {
      var args, callback, requestId;
      requestId = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (!(callback = this._sendCallbacks[requestId])) {
        this.log('warn', "Request callback key='" + requestId + "' not found.");
        return;
      }
      callback.apply(null, args);
      return delete this._sendCallbacks[requestId];
    };

    TransceiverBridge.prototype.write = function(type, pin, value) {
      if (this.status !== this.STATUS_TYPES.ready) {
        return;
      }
      switch (type) {
        case 'digital':
          return this._widgetBridge.digitalWrite(pin, value);
        case 'analog':
          return this._widgetBridge.analogWrite(pin, value);
        case 'virtual':
          return this._widgetBridge.virtualWrite(pin, value);
      }
    };

    TransceiverBridge.prototype._sendFailureCallback = function(requestId, failureCallback, output) {
      if (!this._sendCallbacks[requestId]) {
        return;
      }
      this.log('warn', "Request key='" + requestId + "' output='" + output + "' was timeout.");
      delete this._sendCallbacks[requestId];
      return failureCallback();
    };

    return TransceiverBridge;

  })(BaseBridge);

  module.exports = TransceiverBridge;

}).call(this);

//# sourceMappingURL=transceiver-bridge.js.map
