// Generated by CoffeeScript 1.10.0

/**
 * @param {number} size
 * @param {string} base
 * @return {string}
 */

(function() {
  var uid;

  uid = function(size, base) {
    var buf, i, j, len, ref;
    size = size != null ? size : 32;
    base = base != null ? base : 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    len = base.length;
    buf = [];
    for (i = j = 0, ref = size - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      buf.push(base[Math.floor(Math.random() * len)]);
    }
    return buf.join('');
  };

  module.exports = uid;

}).call(this);

//# sourceMappingURL=uid.js.map
