// Generated by CoffeeScript 1.10.0
(function() {
  var CustomEvent, Event,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Event = require('./Event');

  CustomEvent = (function(superClass) {
    extend(CustomEvent, superClass);

    function CustomEvent() {
      return CustomEvent.__super__.constructor.apply(this, arguments);
    }

    return CustomEvent;

  })(Event);

  module.exports = CustomEvent;

}).call(this);

//# sourceMappingURL=CustomEvent.js.map
