// Generated by CoffeeScript 1.10.0
(function() {
  var Base, CustomEvent, EventGenerator, NotifyEvent,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('../Base');

  NotifyEvent = require('./NotifyEvent');

  CustomEvent = require('./CustomEvent');

  EventGenerator = (function(superClass) {
    extend(EventGenerator, superClass);


    /**
     * @override
     */

    EventGenerator.prototype.TYPE = 'EventGenerator';

    function EventGenerator(parent) {
      this.generate = bind(this.generate, this);
      var config;
      config = {
        name: 'generator'
      };
      EventGenerator.__super__.constructor.call(this, parent, config, -1);
    }

    EventGenerator.prototype.generate = function(parent, config, index) {
      this.checkConfig(config.event, 'config.event', 'string');
      switch (config.event) {
        case '$notify':
          return new NotifyEvent(parent, config, index);
        default:
          if (config.event.match(/$\$/)) {
            this.log('fatal', "Event '" + config.event + "' is not defined built-in event.");
            return process.exit(1);
          } else {
            return new CustomEvent(parent, config, index);
          }
      }
    };

    return EventGenerator;

  })(Base);

  module.exports = EventGenerator;

}).call(this);

//# sourceMappingURL=EventGenerator.js.map
