// Generated by CoffeeScript 1.10.0
(function() {
  var Server, config, log4js, logger, path, server;

  require('source-map-support').install();

  path = require('path');

  log4js = require('log4js');

  config = require('./config');

  Server = require('./lib/Server');

  log4js.configure(path.normalize(__dirname + '/./log4js-config.json'), {
    cwd: path.normalize(__dirname + '/.')
  });

  logger = log4js.getLogger('system');

  server = new Server(config, logger);

}).call(this);

//# sourceMappingURL=index.js.map
