// Generated by CoffeeScript 1.10.0
(function() {
  var Blynk, boardConfig, config, core, i, len, log4js, options, path, ref, v1;

  path = require('path');

  Blynk = require('blynk-library');

  log4js = require('log4js');

  core = './lib/core';

  config = './config';

  log4js.configure(path.normalize(__dirname + '/./log4js-config.json'), {
    cwd: path.normalize(__dirname + '/.')
  });

  core.logger = log4js.getLogger('system');

  ref = config.boards;
  for (i = 0, len = ref.length; i < len; i++) {
    boardConfig = ref[i];
    core.boardsblynk = new Blynk.Blynk('', options = {
      certs_path: './node_modules/blynk-library/certs/'
    });
  }

  v1 = new blynk.VirtualPin(1);

  v1.on('write', function(param) {
    return console.log('V1 write: ' + param);
  });

}).call(this);

//# sourceMappingURL=index.js.map
