// Generated by CoffeeScript 1.10.0
(function() {
  var Base, EventEmitter, dot,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  EventEmitter = require('events');

  dot = require('dot-object');

  Base = (function(superClass) {
    extend(Base, superClass);


    /**
     * @const
     * @type {string}
     */

    Base.prototype.TYPE = 'Base';


    /**
     * @public
     * @type {number}
     */

    Base.prototype.index = -1;


    /**
     * @protected
     * @type {string}
     */

    Base.prototype.name = '';


    /**
     * @protected
     * @type {Base}
     */

    Base.prototype._parent = null;


    /**
     * @protected
     * @type {Logger}
     */

    Base.prototype._logger = null;


    /**
     * @constructor
     * @param {Base} parent
     * @param {Object} config
     * @param {number} vPin
     * @param {Logger} logger
     */

    function Base(parent, config, index, logger) {
      this._allKeyLabel = bind(this._allKeyLabel, this);
      this._keyLabel = bind(this._keyLabel, this);
      this._checkConfig = bind(this._checkConfig, this);
      this.log = bind(this.log, this);
      var ref, ref1;
      this._parent = parent;
      this.index = index;
      this._logger = (ref = (ref1 = this._parent) != null ? ref1._logger : void 0) != null ? ref : logger;
      this.name = this._checkConfig(config, 'name', 'string');
      this.log('trace', "Constructing " + this.constructor.name + " object.");
    }

    Base.prototype.log = function() {
      var args, level, ref, ref1;
      level = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (this._parent) {
        return (ref = this._logger).log.apply(ref, [level, this._allKeyLabel()].concat(slice.call(args)));
      } else {
        return (ref1 = this._logger).log.apply(ref1, [level].concat(slice.call(args)));
      }
    };

    Base.prototype._checkConfig = function(config, key, type, defaultValue) {
      var target;
      if (defaultValue == null) {
        defaultValue = void 0;
      }
      if ((typeof config !== 'object') || Array.isArray(config)) {
        this.log('fatal', this._allKeyLabel(), "Check config. 'config' is not object.");
        process.exit(1);
      }
      target = dot.pick(key, config);
      if (typeof target === 'undefined') {
        if (defaultValue !== void 0) {
          return defaultValue;
        } else {
          this.log('fatal', this._allKeyLabel(), "Check config. 'config." + key + "' is undefined.");
          process.exit(1);
        }
      }
      if ((type === 'array' ? !Array.isArray(target) : !(typeof target === type))) {
        this.log('fatal', this._allKeyLabel(), "Check config. 'config." + key + "' type=" + (typeof target) + " is unexpected, expects " + type + ".");
        process.exit(1);
      }
      return target;
    };

    Base.prototype._keyLabel = function() {
      if (this.index >= 0) {
        return "[" + this.TYPE + "(" + this.index + "-" + this.name + ")]";
      } else {
        return "[" + this.TYPE + "]";
      }
    };

    Base.prototype._allKeyLabel = function() {
      var args, ref;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (this._parent) {
        return (ref = this._parent)._allKeyLabel.apply(ref, [this._keyLabel()].concat(slice.call(args)));
      } else {
        return args.join(' ');
      }
    };

    return Base;

  })(EventEmitter);

  module.exports = Base;

}).call(this);

//# sourceMappingURL=base.js.map
