// Generated by CoffeeScript 1.10.0
(function() {
  var Blynk, Board, Bridge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice;

  Blynk = require('blynk-library');

  Bridge = require('./Bridge');

  Board = (function() {

    /**
     * @public
     * @type {string}
     */
    Board.prototype.name = '';


    /**
     * @public
     * @type {Blynk.Blynk}
     */

    Board.prototype.blynk = null;


    /**
     * @protected
     * @type {Server}
     */

    Board.prototype._server = null;


    /**
     * @public
     * @type {Blynk.Blynk.VirtualPin}
     */

    Board.prototype._inputVPin = null;


    /**
     * @public
     * @type {Object.<Bridge>}
     */

    Board.prototype.bridges = null;


    /**
     * @constructor
     */

    function Board(server, config) {
      this._onInputVPin = bind(this._onInputVPin, this);
      this._onConnect = bind(this._onConnect, this);
      this.log = bind(this.log, this);
      var bridgeConfig, i, j, len, ref;
      this._server = server;
      if (!(typeof config === 'object')) {
        this.log('fatal', "Board config is invalid, expects object.");
        process.exit(1);
      }
      if (!(typeof config.name === 'string') || !config.name) {
        this.log('fatal', "Board config.name is invalid, expect string.");
        process.exit(1);
      }
      this.name = config.name;
      if (!(typeof config.token === 'string') || !config.token) {
        this.log('fatal', "Board token setting was invalid, expect string.");
        process.exit(1);
      }
      this.log('debug', "Auth dummy blynk board was started.");
      this.blynk = new Blynk.Blynk(config.token, {
        certs_path: './node_modules/blynk-library/certs/'
      });
      this.log('debug', "Construct Input Virtual Pin 0 was started.");
      this._inputVPin = new this.blynk.VirtualPin(0);
      this.log('debug', "Construct Input Virtual Pin 0 was finished.");
      this.log('debug', "Construct Bridge objects was started.");
      this.bridges = {};
      i = 1;
      ref = config.bridges;
      for (j = 0, len = ref.length; j < len; j++) {
        bridgeConfig = ref[j];
        this.bridges[bridgeConfig.name] = new Bridge(this, bridgeConfig, i++);
      }
      this.log('debug', "Construct Bridge objects was finished.");
      this._inputVPin.on('write', this._onInputVPin);
      this.blynk.on('connect', this._onConnect);
    }


    /**
     * @public
     */

    Board.prototype.log = function() {
      var args, level, ref;
      level = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref = this._server).log.apply(ref, [level, "[Board-" + this.name + "]"].concat(slice.call(args)));
    };

    Board.prototype._onConnect = function() {
      var bridge, bridgeName, ref, results;
      this.log('debug', "Auth dummy blynk board was finished.");
      ref = this.bridges;
      results = [];
      for (bridgeName in ref) {
        bridge = ref[bridgeName];
        results.push(bridge.connect());
      }
      return results;
    };

    Board.prototype._onInputVPin = function(param) {
      var bridgeName, eventArgs, eventName, params, ref;
      params = param[0].split(',');
      if (params.length < 2) {
        this.log('error', "Input data '" + param + "' is invalid format.");
        return;
      }
      bridgeName = params[0];
      eventName = params[1];
      eventArgs = params.splice(2);
      this.log('debug', "Receive input data, bridge='" + bridgeName + "' event='" + eventName + "' args=" + (JSON.stringify(eventArgs)));
      if (!this.bridges[bridgeName]) {
        this.log('warn', "Bridge '" + bridgeName + "' was not found.");
        return;
      }
      if (this.bridges[bridgeName].listeners(eventName).length === 0) {
        this.log('warn', "Bridge '" + bridgeName + "' not have '" + eventName + "' event.");
        return;
      }
      return (ref = this.bridges[bridgeName]).emit.apply(ref, [eventName].concat(slice.call(eventArgs)));
    };

    return Board;

  })();

  module.exports = Board;

}).call(this);

//# sourceMappingURL=Board.js.map
