// Generated by CoffeeScript 1.10.0
(function() {
  var BridgeBuiltInEvent, BridgePing,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BridgePing = require('./BridgePing');

  BridgeBuiltInEvent = (function(superClass) {
    extend(BridgeBuiltInEvent, superClass);


    /**
     * @override
     */

    function BridgeBuiltInEvent(board, config, vPin) {
      this._onPushbullet = bind(this._onPushbullet, this);
      this._onLog = bind(this._onLog, this);
      BridgeBuiltInEvent.__super__.constructor.call(this, board, config, vPin);
      this.on('$log', this._onLog);
      this.on('$pushbullet', this._onPushbullet);
    }

    BridgeBuiltInEvent.prototype._onLog = function(message) {
      return this.log('info', message);
    };

    BridgeBuiltInEvent.prototype._onPushbullet = function(message) {};

    return BridgeBuiltInEvent;

  })(BridgePing);

  module.exports = BridgeBuiltInEvent;

}).call(this);

//# sourceMappingURL=BridgeBuiltInEvent.js.map
