// Generated by CoffeeScript 1.10.0
(function() {
  var BridgeBase, EventEmitter,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  EventEmitter = require('events').EventEmitter;

  BridgeBase = (function(superClass) {
    extend(BridgeBase, superClass);


    /**
     * @const
     * @type {Object}
     */

    BridgeBase.prototype.STATUS_TYPE = {
      constructing: {
        label: 'Constructing'
      },
      connecting: {
        label: 'Connecting'
      },
      ready: {
        label: 'Ready'
      },
      error: {
        label: 'Error'
      }
    };


    /**
     * @public
     * @type {string}
     */

    BridgeBase.prototype.name = '';


    /**
     * @public
     * @type {Object}
     */

    BridgeBase.prototype.status = BridgeBase.prototype.STATUS_TYPE.constructing;


    /**
     * @protected
     * @type {Board}
     */

    BridgeBase.prototype._board = null;


    /**
     * @protected
     * @type {string}
     */

    BridgeBase.prototype._token = '';


    /**
     * @protected
     * @type {Blynk.Blynk.WidgetBridge}
     */

    BridgeBase.prototype._widgetBridge = null;


    /**
     * @constructor
     * @param {Board} board
     * @param {Object} config
     * @param {number} vPin
     */

    function BridgeBase(board, config, vPin) {
      this.log = bind(this.log, this);
      this.connect = bind(this.connect, this);
      this._board = board;
      if (!(typeof config === 'object')) {
        this.log('fatal', "Bridge config is invalid, expects object.");
        process.exit(1);
      }
      if (!(typeof config.name === 'string') || !config.name) {
        this.log('fatal', "Bridge config.name is invalid, expects string.");
        process.exit(1);
      }
      this.name = config.name;
      if (!(typeof config.token === 'string') || !config.token) {
        this.log('fatal', "Bridge config.token is invalid, expects string.");
        process.exit(1);
      }
      this._token = config.token;
      this._widgetBridge = new this._board.blynk.WidgetBridge(vPin);
    }


    /**
     * @public
     */

    BridgeBase.prototype.connect = function() {
      this.status = this.STATUS_TYPE.connecting;
      this._widgetBridge.setAuthToken(this._token);
      return this.status = this.STATUS_TYPE.ready;
    };

    BridgeBase.prototype.log = function() {
      var args, level, ref;
      level = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return (ref = this._board).log.apply(ref, [level, "[Bridge-" + this.name + "]"].concat(slice.call(args)));
    };

    return BridgeBase;

  })(EventEmitter);

  module.exports = BridgeBase;

}).call(this);

//# sourceMappingURL=BridgeBase.js.map
