// Generated by CoffeeScript 1.10.0
(function() {
  var BridgeBuiltInEvent, BridgeCustomEvent,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BridgeBuiltInEvent = require('./BridgeBuiltInEvent');

  BridgeCustomEvent = (function(superClass) {
    extend(BridgeCustomEvent, superClass);


    /**
     * @override
     */

    function BridgeCustomEvent(parent, config, index) {
      BridgeCustomEvent.__super__.constructor.call(this, parent, config, index);
    }

    return BridgeCustomEvent;

  })(BridgeBuiltInEvent);

  module.exports = BridgeCustomEvent;

}).call(this);

//# sourceMappingURL=BridgeCustomEvent.js.map
