// Generated by CoffeeScript 1.10.0
(function() {
  var core;

  core = {
    logger: null,
    blynk: null,
    inputVPin: null,
    bridges: {}
  };

  module.exports = core;

}).call(this);

//# sourceMappingURL=core.js.map
