// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Notifier,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Base = require('./Base');

  Notifier = (function(superClass) {
    extend(Notifier, superClass);


    /**
     * @override
     */

    Notifier.prototype.TYPE = 'Notifier';


    /**
     * @override
     */

    function Notifier(server, config, index) {
      this._onNotify = bind(this._onNotify, this);
      Notifier.__super__.constructor.call(this, server, config, index);
      this.on('$notify', this._onNotify);
    }

    Notifier.prototype._onNotify = function() {
      var args, logLevel, message, options, ref, ref1;
      options = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      logLevel = (ref = options != null ? options.level : void 0) != null ? ref : 'info';
      message = (ref1 = options != null ? options.message : void 0) != null ? ref1 : '%s';
      message = util.format.apply(util, [message].concat(slice.call(args)));
      return this.log('info', message);
    };

    return Notifier;

  })(Base);

  module.exports = Notifier;

}).call(this);

//# sourceMappingURL=Notifier.js.map
