// Generated by CoffeeScript 1.10.0
(function() {
  var Action, Base,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Base = require('../base');

  Action = (function(superClass) {
    extend(Action, superClass);


    /**
     * @override
     */

    Action.prototype.TYPE = 'Action';


    /**
     * @protected
     * @type {string}
     */

    Action.prototype.action = '';


    /**
     * @override
     */

    function Action(parent, config, index) {
      this.run = bind(this.run, this);
      Action.__super__.constructor.call(this, parent, config, index);
      this.checkConfig(config.action, 'config.action', 'string');
      this.action = config.action;
    }


    /**
     * @public
     * @param {Base} caller
     */

    Action.prototype.run = function() {
      var args, caller;
      caller = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return this.log('error', "Action.run is abstract function");
    };

    return Action;

  })(Base);

  module.exports = Action;

}).call(this);

//# sourceMappingURL=action.js.map
