// Generated by CoffeeScript 1.10.0
(function() {
  var Action, CustomAction,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Action = require('./action');

  CustomAction = (function(superClass) {
    extend(CustomAction, superClass);

    function CustomAction() {
      return CustomAction.__super__.constructor.apply(this, arguments);
    }

    return CustomAction;

  })(Action);

  module.exports = CustomAction;

}).call(this);

//# sourceMappingURL=custom-action.js.map
