// Generated by CoffeeScript 1.10.0
(function() {
  var Action, PinAction,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Action = require('./action');

  PinAction = (function(superClass) {
    extend(PinAction, superClass);


    /**
     * @protected
     * @type {string}
     */

    PinAction.prototype._next = '';


    /**
     * @protected
     * @type {string}
     */

    PinAction.prototype._pinType = '';


    /**
     * @protected
     * @type {number}
     */

    PinAction.prototype._pin = -1;


    /**
     * @override
     */

    function PinAction(parent, config, index) {
      PinAction.__super__.constructor.call(this, parent, config, index);
      this._pinType = this._checkConfig(config, 'pinType', ['in', 'digital', 'analog', 'virtual']);
      this._pin = this._checkConfig(config, 'pin', 'number');
      this._next = this._addSubAction(parent, config, 'next');
    }

    return PinAction;

  })(Action);

  module.exports = PinAction;

}).call(this);

//# sourceMappingURL=pin-action.js.map
