// Generated by CoffeeScript 1.10.0
(function() {
  var Action, ReadAction,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Action = require('./action');

  ReadAction = (function(superClass) {
    extend(ReadAction, superClass);


    /**
     * @protected
     * @type {string}
     */

    ReadAction.prototype._next = '';


    /**
     * @protected
     * @type {string}
     */

    ReadAction.prototype._pinType = '';


    /**
     * @protected
     * @type {number}
     */

    ReadAction.prototype._pin = -1;


    /**
     * @override
     */

    function ReadAction(parent, config, index) {
      this.run = bind(this.run, this);
      ReadAction.__super__.constructor.call(this, parent, config, index);
      this._next = this._checkConfig(config, 'next', 'string');
      this._pinType = this._checkConfig(config, 'pinType', 'string');
      this._pin = this._checkConfig(config, 'pin', 'number');
    }


    /**
     * @override
     */

    ReadAction.prototype.run = function() {
      var args, bridge, output;
      bridge = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      output = '';
      switch (this._pinType) {
        case 'digital':
          output = 'dr';
          break;
        case 'analog':
          output = 'ar';
          break;
        case 'virtual':
          output = 'vr';
      }
      output += ',' + this._pin;
      return bridge.send(output, (function(_this) {
        return function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return bridge.emit.apply(bridge, [_this._next, bridge].concat(slice.call(args)));
        };
      })(this));
    };

    return ReadAction;

  })(Action);

  module.exports = ReadAction;

}).call(this);

//# sourceMappingURL=read-action.js.map
