// Generated by CoffeeScript 1.10.0
(function() {
  var PinAction, WriteAction,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  PinAction = require('./pin-action');

  WriteAction = (function(superClass) {
    extend(WriteAction, superClass);


    /**
     * @protected
     * @type {number}
     */

    WriteAction.prototype._value = -1;


    /**
     * @override
     */

    function WriteAction(parent, config, index) {
      this.run = bind(this.run, this);
      WriteAction.__super__.constructor.call(this, parent, config, index);
      this._value = this._checkConfig(config, 'value', 'number');
    }


    /**
     * @override
     */

    WriteAction.prototype.run = function() {
      var args, bridge, command;
      bridge = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      switch (this._pinType) {
        case 'digital':
          command = 'dw';
          break;
        case 'analog':
          command = 'aw';
          break;
        case 'virtual':
          command = 'vw';
      }
      return bridge.send(command, this._pin, this._value, (function(_this) {
        return function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          if (_this._next) {
            return bridge.emit.apply(bridge, [_this._next, bridge].concat(slice.call(args)));
          }
        };
      })(this));
    };

    return WriteAction;

  })(PinAction);

  module.exports = WriteAction;

}).call(this);

//# sourceMappingURL=write-action.js.map
