// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Notifier,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Base = require('./../base');

  Notifier = (function(superClass) {
    extend(Notifier, superClass);


    /**
     * @protected
     * @type {number}
     */

    Notifier.prototype._firstDelay = 3000;


    /**
     * @protected
     * @type {number}
     */

    Notifier.prototype._nextDelay = 10000;


    /**
     * @private
     * @type {boolean}
     */

    Notifier.prototype._waiting = false;


    /**
     * @private
     * @type {Array}
     */

    Notifier.prototype._messages = null;


    /**
     * @override
     */

    function Notifier(server, config) {
      this._makeMessage = bind(this._makeMessage, this);
      this._sendNext = bind(this._sendNext, this);
      this._sendFirst = bind(this._sendFirst, this);
      this._onSend = bind(this._onSend, this);
      this._onNotify = bind(this._onNotify, this);
      Notifier.__super__.constructor.call(this, server, config);
      this._firstDelay = this._checkConfig(config, 'firstDelay', 'number', this._firstDelay);
      this._nextDelay = this._checkConfig(config, 'nextDelay', 'number', this._nextDelay);
      this._messages = [];
      this.on('notify', this._onNotify);
      this.on('send', this._onSend);
    }


    /**
     * @protected
     * @param {Action} action
     * @param {Array} args
     */

    Notifier.prototype._onNotify = function() {
      var action, args, message;
      action = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      message = this._makeMessage.apply(this, [action].concat(slice.call(args)));
      this._messages.push(message);
      if (!this._waiting) {
        this._waiting = true;
        return setTimeout(this._sendFirst, this._firstDelay);
      }
    };


    /**
     * @protected
     * @param {Array.<string>} messages
     */

    Notifier.prototype._onSend = function(messages) {};


    /**
     * @protected
     */

    Notifier.prototype._sendFirst = function() {
      this.emit('send', this._messages);
      this._messages = [];
      return setTimeout(this._sendNext, this._nextDelay);
    };


    /**
     * @private
     */

    Notifier.prototype._sendNext = function() {
      if (this._messages.length === 0) {
        return this._waiting = false;
      } else {
        this.emit('send', this._messages);
        this._messages = [];
        return setTimeout(this._sendNext, this._nextDelay);
      }
    };


    /**
     * @protected
     * @param {Action} action
     * @param {Array} args
     * @return {string}
     */

    Notifier.prototype._makeMessage = function() {
      var action, args, message, ref;
      action = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      message = (ref = action.message) != null ? ref : '%s';
      message = action.allKeyLabel() + ' ' + util.format.apply(util, [message].concat(slice.call(args)));
      return message;
    };

    return Notifier;

  })(Base);

  module.exports = Notifier;

}).call(this);

//# sourceMappingURL=notifier.js.map
